### ISSUE TITLE
[bug] GNOME 48 Update bug: class heritage MessageList.MessageListSection is not an object or null

### ISSUE THREAD

**Issue by KIDult2226** [qwreey/quick-settings-tweaks#197]
## Describe the bug

GNOME 48 reported bug:
TypeError: class heritage MessageList.MessageListSection is not an object or null

Extension quick-settings-tweaks@qwreey: TypeError: class heritage MessageList.MessageListSection is not an object or null
                                                    @file:///~/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/features/widget/notifications.js:134:1

## To Reproduce

Update to gnome 48

## Screenshots

![Image](https://github.com/user-attachments/assets/b506cb7d-8144-4b51-bfff-fcf42dca9f3c)

## Environment

1. gnome-shell version: (ex) GNOME Shell 48
2. distro information:
```
(ex)
NAME="CachyOS"
PRETTY_NAME="CachyOS"
ID=arch
BUILD_ID=rolling
```
3. Extension version: 2.1 - stable

**Comment by eboye** [comment]
I confirm this.

**Comment by mambucodev** [comment]
I have this too, and also other people I know

**Comment by mambucodev** [comment]
Btw, this is more about #171

**Comment by Davidekiller1999** [comment]
I confirm. I have arch with gnome 48 and the extension is broken.

**Comment by fabcard** [comment]
Hello there,
I have CachyOS and after the Gnome 48 update a couple of days ago, the extension is not working anymore.
TypeError: class heritage MessageList.MessageListSection is not an object or null
Thanks in advance.

**Comment by mambucodev** [comment]
I suggest all people having the same issue to just add a 👍 to the issue instead of adding comments. It's been pretty much clarified that GNOME 48 is the cause, so if you don't have other debug info other than that I'd suggest to just 👍 to add visibility.

**Comment by emiltoacs** [comment]
The /ui/messageList.js/MessageListSection class has been removed and replaced by the NotificationMessageGroup. This new class provides expand() and colapse() methods for controlling the expansion state of the message group. This class emits an expand-toggle-requested signal for that.

**Comment by Raviksh96** [comment]
> From the Gnome 48 port extensions:
> 
> The /ui/messageList.js/MessageListSection class has been removed and replaced by the NotificationMessageGroup. This new class provides expand() and colapse() methods for controlling the expansion state of the message group. This class emits an expand-toggle-requested signal for that.
> 
> https://gjs.guide/extensions/upgrading/gnome-shell-48.html#notifications-per-app-group

So, how to implement this in notification.js file of the extension?

**Comment by insane-alt** [comment]
Does the dev know about this issue I am still not able to use the extension.

**Comment by mambucodev** [comment]
> Does the dev know about this issue I am still not able to use the extension.

I think he knows. Idk what the issue is but let's not apply pressure.

**Comment by Davidekiller1999** [comment]
any news?

**Comment by eloymelo** [comment]
> any news?

Nothing yet.

**Comment by qwreey** [comment]
Includes mechanical translation

My company contract is slightly extended, and I have no plans to update within April due to a lot of assignments and exam preparation.

This is entirely a problem with the quick settings tweaker. Please do not report this to the gnome team. However, we will (definitely) break 47 compatibility to do this. For notification 's grouping functionality, the gnome team almost completely rewrote that part, and it's now almost a completely different element. It is not a matter of simply connecting. We need to solve fade effect.

Maybe someone can try it. Before March, before I started work at the company, I did as much as I could to prepare for gnome 48, so there should be no problem as long as notifications are resolved.

**Comment by lsakdf** [comment]
just comment out lines 15 and 49 in extension.js

![Image](https://github.com/user-attachments/assets/638028c7-2c93-4601-83c1-25f25578964a)

**Comment by mricewolf0110** [comment]
> just comment out lines 15 and 49 in extension.js
> 
> ![Image](https://github.com/user-attachments/assets/638028c7-2c93-4601-83c1-25f25578964a)

I got TypeError: patchObject is undefined. It's still not working.

**Comment by freddyw** [comment]
> > just comment out lines 15 and 49 in extension.js
> > ![Image](https://github.com/user-attachments/assets/638028c7-2c93-4601-83c1-25f25578964a)
> 
> I got TypeError: patchObject is undefined. It's still not working.

Comment lines 18 and 52 as well. Not a solution, just a quick (sort of a) fix.

**Comment by Raviksh96** [comment]
> > > just comment out lines 15 and 49 in extension.js
> > > ![Image](https://github.com/user-attachments/assets/638028c7-2c93-4601-83c1-25f25578964a)
> > 
> > 
> > I got TypeError: patchObject is undefined. It's still not working.
> 
> Comment lines 18 and 52 as well. Not a solution, just a quick (sort of a) fix.

![Image](https://github.com/user-attachments/assets/2496738f-3c41-4700-b928-99aaa1aa2716)

This happened with me after commenting out line 15, 18, 49 and 52. Any Solutions?

**Comment by Raviksh96** [comment]
> > > > just comment out lines 15 and 49 in extension.js
> > > > ![Image](https://github.com/user-attachments/assets/638028c7-2c93-4601-83c1-25f25578964a)
> > > 
> > > 
> > > I got TypeError: patchObject is undefined. It's still not working.
> > 
> > 
> > Comment lines 18 and 52 as well. Not a solution, just a quick (sort of a) fix.
> 
> ![Image](https://github.com/user-attachments/assets/2496738f-3c41-4700-b928-99aaa1aa2716)
> 
> This happened with me after commenting out line 15, 18, 49 and 52. Any Solutions?
> 
> ![Image](https://github.com/user-attachments/assets/d359ad05-93ae-468a-8e07-2da576af35ab)

Nvm, this was my mistake, I turned on layout border from debug menu.

**Comment by valentesolucoes** [comment]
I confirm this too.

**Comment by sannidhyaroy** [comment]
> This happened with me after commenting out line 15, 18, 49 and 52. Any Solutions?

Commenting this out will remove the Notification Widget feature in the Quick Settings Panel, right? Does disabling the toggle to hide the notifications in the Date Menu works after this?

**Comment by Raviksh96** [comment]
> > This happened with me after commenting out line 15, 18, 49 and 52. Any Solutions?
> 
> Commenting this out will remove the Notification Widget feature in the Quick Settings Panel, right? Does disabling the toggle to  work after this?

In my case, after disabling the toggle to hide the notifications in the date menu isn't working, I need to follow above given steps again to get it working.

**Comment by eloymelo** [comment]
The best approach to this (if you don't want to do it by yourself) is to wait for an update from the maintainer of the extension.

**Comment by sannidhyaroy** [comment]
> In my case, after disabling the toggle to hide the notifications in the date menu isn't working, I need to follow above given steps again to get it working.

No, what I asked is does commenting out the mentioned lines (15, 18, 49 and 52), remove the notifications feature in the Quick Settings Panel. If that's the case, then you should be able to get notifications in the date menu back, until the dev finished migrating to Gnome 48.

I'm currently not on Gnome 48, as I rolled back using snapper, as soon as I found my extensions broken, so I can't test this out.

**Comment by Raviksh96** [comment]
> > In my case, after disabling the toggle to hide the notifications in the date menu isn't working, I need to follow above given steps again to get it working.
> 
> No, what I asked is does commenting out the mentioned lines (15, 18, 49 and 52), remove the notifications feature in the Quick Settings Panel. If that's the case, then you should be able to get notifications in the date menu back, until the dev finished migrating to Gnome 48.
> 
> I'm currently not on Gnome 48, as I rolled back using snapper, as soon as I found my extensions broken, so I can't test this out.

Yes, you'll get the notifications with default style in the date menu and notifications stacking also as gnome 48 supports them instead of quick settings panel.

**Comment by NotAF0e** [comment]
Cool the commenting feature fix worked for me. All i wanted to do was hide the aeroplane mode button and keyboard backlight which does nothing :)

**Comment by CatalinGheorghiu** [comment]
@qwreey any chance we could get a fix on this? Thanks

**Comment by ChaitanyaThaker** [comment]
I just updated to 25.04 and it stopped working

**Comment by Raviksh96** [comment]
> I just updated to 25.04 and it stopped working

A temporary solution is mentioned [here](https://github.com/qwreey/quick-settings-tweaks/issues/197#issuecomment-2812489835) and [here](https://github.com/qwreey/quick-settings-tweaks/issues/197#issuecomment-2812973570) until @qwreey updates the support for gnome 48.

**Comment by Gabbar-v7** [comment]
> > i just fixed it with some enhancements for better compatibility with gnome 48. PR created and waiting for review, but you might clone it and install it manually if you don't wanna wait the whole release cycle.
> 
> Can you give me a step-by-step guide starting from downloading the zip from your fork and installing it in Ubuntu 25.04, Gnome 48?

Here's how to install the fixed extension by @SweidHussameddin 
1. Download the fix from [](https://github.com/SweidHussameddin/quick-settings-tweaks/tree/fix-comp-issue-with-gnome-48) as .zip or clone the repo and switch to fix-comp-with-gnome-48 branch.
2. cd into the folder and open it in an editor like vscode.
3. Run the following on bash terminal to install deps:
```bash
npm i 
```
Note: npm is required download it from package manager
4. Then build and install the extension:
```bash
./install.sh build && ./install.sh install-enable
```

**Comment by qwreey** [comment]
Fixed in 2.2
